version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.141.59-copernicium
    volumes:
      - ./selenium/firefox:/selenium/firefox
    environment:
      - HUB_PORT=4444
    ports:
      - 4444:4444
    networks:
      - <project_name>-network
