version: '2'
services:
  varnish:
    image: million12/varnish
    volumes:
      - ./varnish:/tmp/
    environment:
      VCL_CONFIG: "/tmp/varnish.vcl"
      VARNISHD_PARAMS: "-T localhost:6082 -S /etc/varnish/secret -p default_ttl=3600 -p default_grace=3600"
    ports:
      - "80:80"
    depends_on:
      - loadbalancer
    networks:
      - <project_name>-network

  loadbalancer:
    image: nginx
    volumes:
    - ./nginx/balancer.template:/etc/nginx/conf.d/balancer.template
    - ./nginx/domain.key:/etc/nginx/domain.key
    - ./nginx/domain.crt:/etc/nginx/domain.crt
    ports:
    - "8081:80"
    - "443:443"
    environment:
    - NGINX_HOST=localhost/magento
    - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/balancer.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - minion_1 
      - minion_2
      - minion_3
    networks:
      - <project_name>-network
  
  minion_1:
    image: viniciusbord9/magento2:varnish
    # build: .
    ports:
      - "8082:8080"
      - "9001:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - ./src:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      PORT: 8080
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network
  
  minion_2:
    image: viniciusbord9/magento2:varnish
    # build: .
    ports:
      - "8083:8080"
      - "9002:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - ./src:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      PORT: 8080
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network

  minion_3:
    image: viniciusbord9/magento2:varnish
    # build: .
    ports:
      - "8084:8080"
      - "9003:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - ./src:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      PORT: 8080
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network

  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - <project_name>-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - <project_name>-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local


