#!/usr/bin/env bash
if [ "$1" = "varnish" ]
then
	docker-compose -f docker-compose.varnish.yml stop
elif [ "$1" = "loadbalancer" ] 
then
	docker-compose -f docker-compose.loadbalancer.yml stop
else
	docker-compose stop
fi
